apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-url-secret
  namespace: n8n
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:xxx711717@postgres-global-external.database.svc.cluster.local:5432/n8n"