apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 72.56.72.77-72.56.72.77  # LAN pool for LoadBalancer EXTERNAL-IP
