apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path    # <-- Здесь добавляем
  resources:
    requests:
      storage: 10Gi