apiVersion: v1
kind: ConfigMap
metadata:
 name: qdrant-config
 namespace: qdrant
 labels:
  app: qdrant
data:
 config.yaml: |
  service:
   http_port: 6333
   grpc_port: 6334
  storage:
   optimizers:
    default_segment_number: 2
    flush_interval_sec: 5
   wal:
    wal_capacity_mb: 64
    wal_segments_ahead: 0
  cluster:
   enabled: false
