apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb
data:
  MONGO_INITDB_DATABASE: n8n
  MONGODB_REPLICA_SET_NAME: rs0
  MONGODB_PORT_NUMBER: "27017"
  MONGODB_ENABLE_JOURNAL: "true"