apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  mongodb-root-password: eHh4NzExNzE3WFhY
  mongodb-username: YWRtaW4=
  mongodb-replica-set-key: TnQvTHk0aEkvTnQ2M2FIY3ZiN25JaUoycXdtc1hFTndkaVlDcGpqQXM5UT0=