apiVersion: v1
kind: Secret
metadata:
 name: mongo-express-url
 namespace: mongodb
type: Opaque
stringData:
 ME_CONFIG_MONGODB_URL: "mongodb://admin:xxx711717XXX@mongodb-service:27017/?authSource=admin&replicaSet=rs0"
