apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongodb
type: Opaque
stringData:
  ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  ME_CONFIG_MONGODB_ADMINPASSWORD: xxx711717XXX
  ME_CONFIG_MONGODB_SERVER: mongodb-service