apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-kustomize-data
  namespace: rabbitmq
  labels:
    app: rabbitmq-kustomize
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
