apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-kustomize
  namespace: rabbitmq
  labels:
    app: rabbitmq-kustomize
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-kustomize
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
