apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: n8n
spec:
  defaultCertificate:
    secretName: n8n-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.steel-designer-engineer.ru`)
      kind: Rule
      services:
        - name: n8n
          port: 5678
  tls:
    certResolver: letsencrypt

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: redis-tls
  namespace: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`redis.steel-designer-engineer.ru`)
      kind: Rule
      services:
        - name: redis
          port: 6379
  tls:
    certResolver: letsencrypt